[package]
name = "db_traits"
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "db_traits"
path = "lib.rs"

[features]
sqlcipher = ["rusqlite/sqlcipher"]

[dependencies]
thiserror = "~2.0"

[dependencies.edn]
path = "../../edn"

[dependencies.core_traits]
path = "../../core-traits"

[dependencies.sql_traits]
path = "../sql-traits"

[dependencies.rusqlite]
version = "~0.40"
features = ["limits", "bundled"]

[lints]
workspace = true
