[package]
name = "mentat_core"
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"

[dependencies]
chrono = { version = "~0.4", features = ["serde"] }
enumset = "1.1"
indexmap = "~2.14"
ordered-float = { version = "5.3", features = ["serde"] }
uuid = { version = "~1.25", features = ["v4", "serde"] }

[dependencies.core_traits]
path = "../core-traits"

[dependencies.edn]
path = "../edn"
features = ["serde_support"]

[lints]
workspace = true
